/*
 * Created on 2025-03-20 ( 10:03:13 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import static junit.framework.TestCase.assertNotNull;

import org.demo.entities.tooling.JpaTest;
import org.junit.Test;

public class AuditLogJpaTest extends JpaTest {

    public static AuditLog getInitEntity() {
    	AuditLog entity = new AuditLog();
		// logId is auto-incremented => do not set
		entity.setUserId( UsersJpaTest.getInitEntity().getUserId() ) ;
		entity.setEmployeeId( EmployeeJpaTest.getInitEntity().getEmployeeId() ) ;
		entity.setAction( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setTableName( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setRecordId( Integer.valueOf(100) ) ;
		entity.setTimestamp( java.time.LocalDateTime.parse("2001-05-21T01:46:52") ) ;
    	return entity;
	}
	
    private AuditLog createEntity() {
    	AuditLog entity = new AuditLog();
		// logId is auto-incremented => do not set
		entity.setUserId( UsersJpaTest.getInitEntity().getUserId() ) ;
		entity.setEmployeeId( EmployeeJpaTest.getInitEntity().getEmployeeId() ) ;
		entity.setAction( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setTableName( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setRecordId( Integer.valueOf(200) ) ;
		entity.setTimestamp( java.time.LocalDateTime.parse("2002-05-21T02:46:52") ) ;
    	return entity;
    }


    private Object getEntityKey(AuditLog entity) {
    	return entity.getLogId();
    }

    @Test
    public void testFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }
    
    @Test
    public void testPersistFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

    @Test
    public void testMergeFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

}
