/*
 * Created on 2025-03-20 ( 10:03:14 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import static junit.framework.TestCase.assertNotNull;

import org.demo.entities.tooling.JpaTest;
import org.junit.Test;

public class CustomerOrderJpaTest extends JpaTest {

    public static CustomerOrder getInitEntity() {
    	CustomerOrder entity = new CustomerOrder();
		// orderId is auto-incremented => do not set
		entity.setEmployeeSellerId( EmployeeJpaTest.getInitEntity().getEmployeeId() ) ;
		entity.setCustomerId( CustomerJpaTest.getInitEntity().getCustomerId() ) ;
		entity.setPaymentMethodId( PaymentMethodsJpaTest.getInitEntity().getPaymentMethodId() ) ;
		entity.setAddressId( AddressesJpaTest.getInitEntity().getAddressId() ) ;
		entity.setPurchaseDate( java.time.LocalDate.parse("2001-06-22") ) ;
		entity.setTotalPrice( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setStatus( "AAAAAAAAAAAAAAAAAAAA" ) ;
    	return entity;
	}
	
    private CustomerOrder createEntity() {
    	CustomerOrder entity = new CustomerOrder();
		// orderId is auto-incremented => do not set
		entity.setEmployeeSellerId( EmployeeJpaTest.getInitEntity().getEmployeeId() ) ;
		entity.setCustomerId( CustomerJpaTest.getInitEntity().getCustomerId() ) ;
		entity.setPaymentMethodId( PaymentMethodsJpaTest.getInitEntity().getPaymentMethodId() ) ;
		entity.setAddressId( AddressesJpaTest.getInitEntity().getAddressId() ) ;
		entity.setPurchaseDate( java.time.LocalDate.parse("2002-06-22") ) ;
		entity.setTotalPrice( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setStatus( "BBBBBBBBBBBBBBBBBBBB" ) ;
    	return entity;
    }


    private Object getEntityKey(CustomerOrder entity) {
    	return entity.getOrderId();
    }

    @Test
    public void testFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }
    
    @Test
    public void testPersistFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

    @Test
    public void testMergeFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

}
