/*
 * Created on 2025-03-19 ( 17:24:35 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import static junit.framework.TestCase.assertNotNull;

import org.demo.entities.tooling.JpaTest;
import org.junit.Test;

public class EmployeeJpaTest extends JpaTest {

    public static Employee getInitEntity() {
    	Employee entity = new Employee();
		// employeeId is auto-incremented => do not set
		entity.setStoreId( StoreJpaTest.getInitEntity().getStoreId() ) ;
		entity.setStorageNo( StorageJpaTest.getInitEntity().getStorageNo() ) ;
		entity.setFName( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setMName( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setLName( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setEmail( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setGender( "A" ) ;
		entity.setRole( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setSupervisor( EmployeeJpaTest.getInitEntity().getEmployeeId() ) ;
    	return entity;
	}
	
    private Employee createEntity() {
    	Employee entity = new Employee();
		// employeeId is auto-incremented => do not set
		entity.setStoreId( StoreJpaTest.getInitEntity().getStoreId() ) ;
		entity.setStorageNo( StorageJpaTest.getInitEntity().getStorageNo() ) ;
		entity.setFName( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setMName( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setLName( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setEmail( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setGender( "B" ) ;
		entity.setRole( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setSupervisor( EmployeeJpaTest.getInitEntity().getEmployeeId() ) ;
    	return entity;
    }


    private Object getEntityKey(Employee entity) {
    	return entity.getEmployeeId();
    }

    @Test
    public void testFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }
    
    @Test
    public void testPersistFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

    @Test
    public void testMergeFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

}
