/*
 * Created on 2025-03-20 ( 10:03:15 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import static junit.framework.TestCase.assertNotNull;

import org.demo.entities.tooling.JpaTest;
import org.junit.Test;

public class PhoneNumbersSupplierJpaTest extends JpaTest {

    public static PhoneNumbersSupplier getInitEntity() {
    	PhoneNumbersSupplier entity = new PhoneNumbersSupplier();
		entity.setPhoneNumber( "AAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setSupplierId( SupplierJpaTest.getInitEntity().getSupplierId() ) ;
    	return entity;
	}
	
    private PhoneNumbersSupplier createEntity() {
    	PhoneNumbersSupplier entity = new PhoneNumbersSupplier();
		entity.setPhoneNumber( "BBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setSupplierId( SupplierJpaTest.getInitEntity().getSupplierId() ) ;
    	return entity;
    }


    private Object getEntityKey(PhoneNumbersSupplier entity) {
    	return entity.getPhoneNumber();
    }

    @Test
    public void testFind() {
    	PhoneNumbersSupplier e = find(PhoneNumbersSupplier.class, getEntityKey(getInitEntity()) );
		assertNotNull(e);
    }
    
    @Test
    public void testPersistFind() {
    	PhoneNumbersSupplier entity = createEntity();
    	Object key = getEntityKey(entity);

    	// if entity doesn't exist yet
    	if ( find(PhoneNumbersSupplier.class, key) == null ) {

	    	// Create with 'persist'
    		persistAndRefresh(entity);
    	
			// Find
			PhoneNumbersSupplier entity2 = find(PhoneNumbersSupplier.class, key);
			assertNotNull(entity2);
        
			// Remove (use only if no risk of referential integrity constraint violation)
			// findAndRemove(PhoneNumbersSupplier.class, key);			
			// assertNull(find(PhoneNumbersSupplier.class, key));
		}
    }

    @Test
    public void testMergeFind() {
    	PhoneNumbersSupplier entity = createEntity();
    	Object key = getEntityKey(entity);

    	// Create or update with 'merge'
    	mergeAndRefresh(entity);
    	
    	// Find
    	PhoneNumbersSupplier entity2 = find(PhoneNumbersSupplier.class, key);
        assertNotNull(entity2);
        
		// Remove (use only if no risk of referential integrity constraint violation)
		// findAndRemove(PhoneNumbersSupplier.class, key);			
        // assertNull(find(PhoneNumbersSupplier.class, key));
    }

}
