/*
 * Created on 2025-03-20 ( 10:03:16 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import static junit.framework.TestCase.assertNotNull;

import org.demo.entities.tooling.JpaTest;
import org.junit.Test;

public class PriceHistoryJpaTest extends JpaTest {

    public static PriceHistory getInitEntity() {
    	PriceHistory entity = new PriceHistory();
		// historyId is auto-incremented => do not set
		entity.setProductId( ProductJpaTest.getInitEntity().getProductId() ) ;
		entity.setPrice( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setChangeDate( java.time.LocalDate.parse("2001-06-22") ) ;
    	return entity;
	}
	
    private PriceHistory createEntity() {
    	PriceHistory entity = new PriceHistory();
		// historyId is auto-incremented => do not set
		entity.setProductId( ProductJpaTest.getInitEntity().getProductId() ) ;
		entity.setPrice( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setChangeDate( java.time.LocalDate.parse("2002-06-22") ) ;
    	return entity;
    }


    private Object getEntityKey(PriceHistory entity) {
    	return entity.getHistoryId();
    }

    @Test
    public void testFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }
    
    @Test
    public void testPersistFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

    @Test
    public void testMergeFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

}
