/*
 * Created on 2025-03-19 ( 17:24:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import static junit.framework.TestCase.assertNotNull;

import org.demo.entities.tooling.JpaTest;
import org.junit.Test;

public class PromotionsJpaTest extends JpaTest {

    public static Promotions getInitEntity() {
    	Promotions entity = new Promotions();
		// promotionId is auto-incremented => do not set
		entity.setCode( "AAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setDescription( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setDiscountPercentage( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setDiscountAmount( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setStartDate( java.time.LocalDate.parse("2001-06-22") ) ;
		entity.setEndDate( java.time.LocalDate.parse("2001-06-22") ) ;
		entity.setIsActive( true ) ;
		entity.setMaxUses( Integer.valueOf(100) ) ;
    	return entity;
	}
	
    private Promotions createEntity() {
    	Promotions entity = new Promotions();
		// promotionId is auto-incremented => do not set
		entity.setCode( "BBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setDescription( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setDiscountPercentage( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setDiscountAmount( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setStartDate( java.time.LocalDate.parse("2002-06-22") ) ;
		entity.setEndDate( java.time.LocalDate.parse("2002-06-22") ) ;
		entity.setIsActive( false ) ;
		entity.setMaxUses( Integer.valueOf(200) ) ;
    	return entity;
    }


    private Object getEntityKey(Promotions entity) {
    	return entity.getPromotionId();
    }

    @Test
    public void testFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }
    
    @Test
    public void testPersistFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

    @Test
    public void testMergeFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

}
