/*
 * Created on 2025-03-19 ( 17:24:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import static junit.framework.TestCase.assertNotNull;

import org.demo.entities.tooling.JpaTest;
import org.junit.Test;

public class ReservedStockJpaTest extends JpaTest {

    public static ReservedStock getInitEntity() {
    	ReservedStock entity = new ReservedStock();
		// reservationId is auto-incremented => do not set
		entity.setStoreId( StoreJpaTest.getInitEntity().getStoreId() ) ;
		entity.setProductId( ProductJpaTest.getInitEntity().getProductId() ) ;
		entity.setQuantity( 100 ) ;
		entity.setReservedAt( java.time.LocalDateTime.parse("2001-05-21T01:46:52") ) ;
		entity.setExpiresAt( java.time.LocalDateTime.parse("2001-05-21T01:46:52") ) ;
    	return entity;
	}
	
    private ReservedStock createEntity() {
    	ReservedStock entity = new ReservedStock();
		// reservationId is auto-incremented => do not set
		entity.setStoreId( StoreJpaTest.getInitEntity().getStoreId() ) ;
		entity.setProductId( ProductJpaTest.getInitEntity().getProductId() ) ;
		entity.setQuantity( 200 ) ;
		entity.setReservedAt( java.time.LocalDateTime.parse("2002-05-21T02:46:52") ) ;
		entity.setExpiresAt( java.time.LocalDateTime.parse("2002-05-21T02:46:52") ) ;
    	return entity;
    }


    private Object getEntityKey(ReservedStock entity) {
    	return entity.getReservationId();
    }

    @Test
    public void testFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }
    
    @Test
    public void testPersistFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

    @Test
    public void testMergeFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

}
