/*
 * Created on 2025-03-19 ( 17:24:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import static junit.framework.TestCase.assertNotNull;

import org.demo.entities.tooling.JpaTest;
import org.junit.Test;

public class ReturnJpaTest extends JpaTest {

    public static Return getInitEntity() {
    	Return entity = new Return();
		// returnId is auto-incremented => do not set
		entity.setOrderId( CustomerOrderJpaTest.getInitEntity().getOrderId() ) ;
		entity.setProductId( ProductJpaTest.getInitEntity().getProductId() ) ;
		entity.setRefundedAmount( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setQuantityReturned( 100 ) ;
		entity.setReason( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setReturnDate( java.time.LocalDate.parse("2001-06-22") ) ;
    	return entity;
	}
	
    private Return createEntity() {
    	Return entity = new Return();
		// returnId is auto-incremented => do not set
		entity.setOrderId( CustomerOrderJpaTest.getInitEntity().getOrderId() ) ;
		entity.setProductId( ProductJpaTest.getInitEntity().getProductId() ) ;
		entity.setRefundedAmount( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setQuantityReturned( 200 ) ;
		entity.setReason( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setReturnDate( java.time.LocalDate.parse("2002-06-22") ) ;
    	return entity;
    }


    private Object getEntityKey(Return entity) {
    	return entity.getReturnId();
    }

    @Test
    public void testFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }
    
    @Test
    public void testPersistFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

    @Test
    public void testMergeFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

}
