/*
 * Created on 2025-03-20 ( 10:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import static junit.framework.TestCase.assertNotNull;

import org.demo.entities.tooling.JpaTest;
import org.junit.Test;

public class StoreInventoryJpaTest extends JpaTest {

    public static StoreInventory getInitEntity() {
    	StoreInventory entity = new StoreInventory();
		entity.setStoreId( StoreJpaTest.getInitEntity().getStoreId() ) ;
		entity.setProductId( ProductJpaTest.getInitEntity().getProductId() ) ;
		entity.setQuantity( 100 ) ;
    	return entity;
	}
	
    private StoreInventory createEntity() {
    	StoreInventory entity = new StoreInventory();
		entity.setStoreId( StoreJpaTest.getInitEntity().getStoreId() ) ;
		entity.setProductId( ProductJpaTest.getInitEntity().getProductId() ) ;
		entity.setQuantity( 200 ) ;
    	return entity;
    }


    private Object getEntityKey(StoreInventory entity) {
		return new StoreInventoryId( entity.getStoreId(), entity.getProductId() );
    }

    @Test
    public void testFind() {
    	StoreInventory e = find(StoreInventory.class, getEntityKey(getInitEntity()) );
		assertNotNull(e);
    }
    
    @Test
    public void testPersistFind() {
    	StoreInventory entity = createEntity();
    	Object key = getEntityKey(entity);

    	// if entity doesn't exist yet
    	if ( find(StoreInventory.class, key) == null ) {

	    	// Create with 'persist'
    		persistAndRefresh(entity);
    	
			// Find
			StoreInventory entity2 = find(StoreInventory.class, key);
			assertNotNull(entity2);
        
			// Remove (use only if no risk of referential integrity constraint violation)
			// findAndRemove(StoreInventory.class, key);			
			// assertNull(find(StoreInventory.class, key));
		}
    }

    @Test
    public void testMergeFind() {
    	StoreInventory entity = createEntity();
    	Object key = getEntityKey(entity);

    	// Create or update with 'merge'
    	mergeAndRefresh(entity);
    	
    	// Find
    	StoreInventory entity2 = find(StoreInventory.class, key);
        assertNotNull(entity2);
        
		// Remove (use only if no risk of referential integrity constraint violation)
		// findAndRemove(StoreInventory.class, key);			
        // assertNull(find(StoreInventory.class, key));
    }

}
