/*
 * Created on 2025-03-20 ( 10:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import static junit.framework.TestCase.assertNotNull;

import org.demo.entities.tooling.JpaTest;
import org.junit.Test;

public class StorageJpaTest extends JpaTest {

    public static Storage getInitEntity() {
    	Storage entity = new Storage();
		// storageNo is auto-incremented => do not set
		entity.setStoreId( StoreJpaTest.getInitEntity().getStoreId() ) ;
		entity.setLocation( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setReorderLevel( 100 ) ;
		entity.setMaxStock( 100 ) ;
		entity.setMinStock( 100 ) ;
    	return entity;
	}
	
    private Storage createEntity() {
    	Storage entity = new Storage();
		// storageNo is auto-incremented => do not set
		entity.setStoreId( StoreJpaTest.getInitEntity().getStoreId() ) ;
		entity.setLocation( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setReorderLevel( 200 ) ;
		entity.setMaxStock( 200 ) ;
		entity.setMinStock( 200 ) ;
    	return entity;
    }


    private Object getEntityKey(Storage entity) {
    	return entity.getStorageNo();
    }

    @Test
    public void testFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }
    
    @Test
    public void testPersistFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

    @Test
    public void testMergeFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

}
