/*
 * Created on 2025-03-20 ( 10:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import static junit.framework.TestCase.assertNotNull;

import org.demo.entities.tooling.JpaTest;
import org.junit.Test;

public class SupplyOrderJpaTest extends JpaTest {

    public static SupplyOrder getInitEntity() {
    	SupplyOrder entity = new SupplyOrder();
		// supplyOrderId is auto-incremented => do not set
		entity.setSupplierId( SupplierJpaTest.getInitEntity().getSupplierId() ) ;
		entity.setProductId( ProductJpaTest.getInitEntity().getProductId() ) ;
		entity.setEmployeeId( EmployeeJpaTest.getInitEntity().getEmployeeId() ) ;
		entity.setQuantityOrdered( 100 ) ;
		entity.setPrice( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setOrderDate( java.time.LocalDate.parse("2001-06-22") ) ;
    	return entity;
	}
	
    private SupplyOrder createEntity() {
    	SupplyOrder entity = new SupplyOrder();
		// supplyOrderId is auto-incremented => do not set
		entity.setSupplierId( SupplierJpaTest.getInitEntity().getSupplierId() ) ;
		entity.setProductId( ProductJpaTest.getInitEntity().getProductId() ) ;
		entity.setEmployeeId( EmployeeJpaTest.getInitEntity().getEmployeeId() ) ;
		entity.setQuantityOrdered( 200 ) ;
		entity.setPrice( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setOrderDate( java.time.LocalDate.parse("2002-06-22") ) ;
    	return entity;
    }


    private Object getEntityKey(SupplyOrder entity) {
    	return entity.getSupplyOrderId();
    }

    @Test
    public void testFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }
    
    @Test
    public void testPersistFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

    @Test
    public void testMergeFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

}
