/*
 * Created on 2025-03-19 ( 17:24:39 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import static junit.framework.TestCase.assertNotNull;

import org.demo.entities.tooling.JpaTest;
import org.junit.Test;

public class UsersJpaTest extends JpaTest {

    public static Users getInitEntity() {
    	Users entity = new Users();
		// userId is auto-incremented => do not set
		entity.setCustomerId( CustomerJpaTest.getInitEntity().getCustomerId() ) ;
		entity.setEmail( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setPasswordHash( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setRole( "AAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setFailedLogins( 100 ) ;
		entity.setLockedUntil( java.time.LocalDateTime.parse("2001-05-21T01:46:52") ) ;
		entity.setCreatedAt( java.time.LocalDateTime.parse("2001-05-21T01:46:52") ) ;
    	return entity;
	}
	
    private Users createEntity() {
    	Users entity = new Users();
		// userId is auto-incremented => do not set
		entity.setCustomerId( CustomerJpaTest.getInitEntity().getCustomerId() ) ;
		entity.setEmail( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setPasswordHash( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setRole( "BBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setFailedLogins( 200 ) ;
		entity.setLockedUntil( java.time.LocalDateTime.parse("2002-05-21T02:46:52") ) ;
		entity.setCreatedAt( java.time.LocalDateTime.parse("2002-05-21T02:46:52") ) ;
    	return entity;
    }


    private Object getEntityKey(Users entity) {
    	return entity.getUserId();
    }

    @Test
    public void testFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }
    
    @Test
    public void testPersistFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

    @Test
    public void testMergeFind() {
		// NB: this entity has an GENERATED PRIMARY KEY
		// Cannot use a generic test with this kind of PK
		// Create a specific test for this case
    }

}
