/*
 * Created on 2025-03-20 ( 10:03:13 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.util.Objects;  import javax.persistence.*;

/**
 * JPA entity class for "Addresses"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Addresses", schema="public", catalog="clothes_store_db" )
public class Addresses implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="Address_ID", nullable=false)
    private int        addressId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Customer_ID", nullable=false)
    private int        customerId ;

    @Column(name="Street", nullable=false, length=100)
    private String     street ;

    @Column(name="City", nullable=false, length=50)
    private String     city ;

    @Column(name="State", length=50)
    private String     state ;

    @Column(name="Postal_Code", nullable=false, length=20)
    private String     postalCode ;

    @Column(name="Country", nullable=false, length=50)
    private String     country ;

    @Column(name="Is_Default", nullable=false)
    private boolean    isDefault ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="Customer_ID", referencedColumnName="Customer_ID", insertable=false, updatable=false)
    private Customer   customer ; 


    /**
     * Constructor
     */
    public Addresses() {
        super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setAddressId( int addressId ) {
        this.addressId = addressId ;
    }
    public int getAddressId() {
        return this.addressId;
    }

    public void setCustomerId( int customerId ) {
        this.customerId = customerId ;
    }
    public int getCustomerId() {
        return this.customerId;
    }

    public void setStreet( String street ) {
        this.street = street ;
    }
    public String getStreet() {
        return this.street;
    }

    public void setCity( String city ) {
        this.city = city ;
    }
    public String getCity() {
        return this.city;
    }

    public void setState( String state ) {
        this.state = state ;
    }
    public String getState() {
        return this.state;
    }

    public void setPostalCode( String postalCode ) {
        this.postalCode = postalCode ;
    }
    public String getPostalCode() {
        return this.postalCode;
    }

    public void setCountry( String country ) {
        this.country = country ;
    }
    public String getCountry() {
        return this.country;
    }

    public void setIsDefault( boolean isDefault ) {
        this.isDefault = isDefault ;
    }
    public boolean isIsDefault() {
        return this.isDefault;
    }

    //--- GETTERS FOR LINKS
    public Customer getCustomer() {
        return this.customer;
    } 

    //--- toString specific method
    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Addresses[");
		sb.append("addressId=").append(addressId);
		sb.append(separator).append("customerId=").append(customerId);
		sb.append(separator).append("street=").append(street);
		sb.append(separator).append("city=").append(city);
		sb.append(separator).append("state=").append(state);
		sb.append(separator).append("postalCode=").append(postalCode);
		sb.append(separator).append("country=").append(country);
		sb.append(separator).append("isDefault=").append(isDefault);
		sb.append("]");
		return sb.toString();
	}

    //--- equals and hashCode methods
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Addresses that = (Addresses) o;
        return addressId == that.addressId#elseObjects.equals(addressId, that.addressId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(addressId);
    }
}