/*
 * Created on 2025-03-20 ( 10:03:14 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.util.Objects;  import java.time.LocalDate;
import javax.persistence.*;

/**
 * JPA entity class for "Customer"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Customer", schema="public", catalog="clothes_store_db" )
public class Customer implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="Customer_ID", nullable=false)
    private int        customerId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="F_Name", nullable=false, length=50)
    private String     fName ;

    @Column(name="M_Name", length=50)
    private String     mName ;

    @Column(name="L_Name", nullable=false, length=50)
    private String     lName ;

    @Column(name="Gender", nullable=false, length=1)
    private String     gender ;

    @Column(name="Birth_Date", nullable=false)
    private LocalDate  birthDate ;

    @Column(name="Email", nullable=false, length=255)
    private String     email ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Customer() {
        super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setCustomerId( int customerId ) {
        this.customerId = customerId ;
    }
    public int getCustomerId() {
        return this.customerId;
    }

    public void setFName( String fName ) {
        this.fName = fName ;
    }
    public String getFName() {
        return this.fName;
    }

    public void setMName( String mName ) {
        this.mName = mName ;
    }
    public String getMName() {
        return this.mName;
    }

    public void setLName( String lName ) {
        this.lName = lName ;
    }
    public String getLName() {
        return this.lName;
    }

    public void setGender( String gender ) {
        this.gender = gender ;
    }
    public String getGender() {
        return this.gender;
    }

    public void setBirthDate( LocalDate birthDate ) {
        this.birthDate = birthDate ;
    }
    public LocalDate getBirthDate() {
        return this.birthDate;
    }

    public void setEmail( String email ) {
        this.email = email ;
    }
    public String getEmail() {
        return this.email;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Customer[");
		sb.append("customerId=").append(customerId);
		sb.append(separator).append("fName=").append(fName);
		sb.append(separator).append("mName=").append(mName);
		sb.append(separator).append("lName=").append(lName);
		sb.append(separator).append("gender=").append(gender);
		sb.append(separator).append("birthDate=").append(birthDate);
		sb.append(separator).append("email=").append(email);
		sb.append("]");
		return sb.toString();
	}

    //--- equals and hashCode methods
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Customer that = (Customer) o;
        return customerId == that.customerId#elseObjects.equals(customerId, that.customerId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(customerId);
    }
}