/*
 * Created on 2025-03-20 ( 10:03:14 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.util.Objects;  import javax.persistence.*;

/**
 * JPA entity class for "Image"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Image", schema="public", catalog="clothes_store_db" )
public class Image implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="Image_ID", nullable=false)
    private int        imageId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Product_ID", nullable=false)
    private int        productId ;

    @Column(name="Image_URL", nullable=false, length=2147483647)
    private String     imageUrl ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="Product_ID", referencedColumnName="Product_ID", insertable=false, updatable=false)
    private Product    product ; 


    /**
     * Constructor
     */
    public Image() {
        super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setImageId( int imageId ) {
        this.imageId = imageId ;
    }
    public int getImageId() {
        return this.imageId;
    }

    public void setProductId( int productId ) {
        this.productId = productId ;
    }
    public int getProductId() {
        return this.productId;
    }

    public void setImageUrl( String imageUrl ) {
        this.imageUrl = imageUrl ;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }

    //--- GETTERS FOR LINKS
    public Product getProduct() {
        return this.product;
    } 

    //--- toString specific method
    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Image[");
		sb.append("imageId=").append(imageId);
		sb.append(separator).append("productId=").append(productId);
		sb.append(separator).append("imageUrl=").append(imageUrl);
		sb.append("]");
		return sb.toString();
	}

    //--- equals and hashCode methods
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Image that = (Image) o;
        return imageId == that.imageId#elseObjects.equals(imageId, that.imageId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(imageId);
    }
}