/*
 * Created on 2025-03-19 ( 17:24:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;


import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.*;

/**
 * JPA entity class for "OrderDetails"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Order_Details", schema="public", catalog="clothes_store_db" )
@IdClass(OrderDetailsId.class)
public class OrderDetails implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="Order_ID", nullable=false)
    private int        orderId ;

    @Id
    @Column(name="Product_ID", nullable=false)
    private int        productId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Quantity", nullable=false)
    private int        quantity ;

    @Column(name="Original_Price", nullable=false)
    private BigDecimal originalPrice ;

    @Column(name="Discount_Amount", nullable=false)
    private BigDecimal discountAmount ;

    @Column(name="Final_Price", nullable=false)
    private BigDecimal finalPrice ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="Order_ID", referencedColumnName="Order_ID", insertable=false, updatable=false)
    private CustomerOrder customerorder ; 

    @ManyToOne
    @JoinColumn(name="Product_ID", referencedColumnName="Product_ID", insertable=false, updatable=false)
    private Product    product ; 


    /**
     * Constructor
     */
    public OrderDetails() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setOrderId( int orderId ) {
        this.orderId = orderId ;
    }
    public int getOrderId() {
        return this.orderId;
    }

    public void setProductId( int productId ) {
        this.productId = productId ;
    }
    public int getProductId() {
        return this.productId;
    }

    public void setQuantity( int quantity ) {
        this.quantity = quantity ;
    }
    public int getQuantity() {
        return this.quantity;
    }

    public void setOriginalPrice( BigDecimal originalPrice ) {
        this.originalPrice = originalPrice ;
    }
    public BigDecimal getOriginalPrice() {
        return this.originalPrice;
    }

    public void setDiscountAmount( BigDecimal discountAmount ) {
        this.discountAmount = discountAmount ;
    }
    public BigDecimal getDiscountAmount() {
        return this.discountAmount;
    }

    public void setFinalPrice( BigDecimal finalPrice ) {
        this.finalPrice = finalPrice ;
    }
    public BigDecimal getFinalPrice() {
        return this.finalPrice;
    }

    //--- GETTERS FOR LINKS
    public CustomerOrder getCustomerorder() {
        return this.customerorder;
    } 

    public Product getProduct() {
        return this.product;
    } 

    //--- toString specific method
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("OrderDetails[");
		sb.append("orderId=").append(orderId);
		sb.append(separator).append("productId=").append(productId);
		sb.append(separator).append("quantity=").append(quantity);
		sb.append(separator).append("originalPrice=").append(originalPrice);
		sb.append(separator).append("discountAmount=").append(discountAmount);
		sb.append(separator).append("finalPrice=").append(finalPrice);
		sb.append("]");
		return sb.toString();
	}
}
