/*
 * Created on 2025-03-19 ( 17:24:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import java.io.Serializable;


/**
 * Composite primary key for entity "OrderDetails" ( stored in table "Order_Details" )
 *
 * @author Telosys
 *
 */
public class OrderDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private int        orderId ;
    
    private int        productId ;
    
    /**
     * Constructor
     */
    public OrderDetailsId() {
        super();
    }

    /**
     * Constructor with values
     * @param orderId 
     * @param productId 
     */
    public OrderDetailsId( Integer orderId, Integer productId ) {
        super();
        this.orderId = orderId ;
        this.productId = productId ;
    }
    
    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setOrderId( int value ) {
        this.orderId = value;
    }
    public int getOrderId() {
        return this.orderId;
    }

    public void setProductId( int value ) {
        this.productId = value;
    }
    public int getProductId() {
        return this.productId;
    }


    //--- equals METHOD
	@Override
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		OrderDetailsId other = (OrderDetailsId) obj; 
		//--- Attribute orderId
		if ( orderId != other.orderId ) return false ; 
		//--- Attribute productId
		if ( productId != other.productId ) return false ; 
		return true; 
	} 
    //--- hashCode METHOD
	@Override
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute orderId
		result = prime * result + orderId;
		//--- Attribute productId
		result = prime * result + productId;
		
		return result; 
	} 
    //--- toString METHOD
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("OrderDetails[");
		sb.append("orderId=").append(orderId);
		sb.append(separator).append("productId=").append(productId);
		sb.append("]");
		return sb.toString();
	}

}
