/*
 * Created on 2025-03-19 ( 17:24:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "PhoneNumbersEmployees"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Phone_Numbers_Employees", schema="public", catalog="clothes_store_db" )
public class PhoneNumbersEmployees implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="Phone_Number", nullable=false, length=20)
    private String     phoneNumber ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Employee_ID", nullable=false)
    private int        employeeId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="Employee_ID", referencedColumnName="Employee_ID", insertable=false, updatable=false)
    private Employee   employee ; 


    /**
     * Constructor
     */
    public PhoneNumbersEmployees() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setPhoneNumber( String phoneNumber ) {
        this.phoneNumber = phoneNumber ;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setEmployeeId( int employeeId ) {
        this.employeeId = employeeId ;
    }
    public int getEmployeeId() {
        return this.employeeId;
    }

    //--- GETTERS FOR LINKS
    public Employee getEmployee() {
        return this.employee;
    } 

    //--- toString specific method
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("PhoneNumbersEmployees[");
		sb.append("phoneNumber=").append(phoneNumber);
		sb.append(separator).append("employeeId=").append(employeeId);
		sb.append("]");
		return sb.toString();
	}
}
