/*
 * Created on 2025-03-19 ( 17:24:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import javax.persistence.*;

/**
 * JPA entity class for "Promotions"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Promotions", schema="public", catalog="clothes_store_db" )
public class Promotions implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="Promotion_ID", nullable=false)
    private int        promotionId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Code", length=20)
    private String     code ;

    @Column(name="Description", nullable=false, length=255)
    private String     description ;

    @Column(name="Discount_Percentage")
    private BigDecimal discountPercentage ;

    @Column(name="Discount_Amount")
    private BigDecimal discountAmount ;

    @Column(name="Start_Date", nullable=false)
    private LocalDate  startDate ;

    @Column(name="End_Date", nullable=false)
    private LocalDate  endDate ;

    @Column(name="Is_Active", nullable=false)
    private boolean    isActive ;

    @Column(name="Max_Uses")
    private Integer    maxUses ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Promotions() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setPromotionId( int promotionId ) {
        this.promotionId = promotionId ;
    }
    public int getPromotionId() {
        return this.promotionId;
    }

    public void setCode( String code ) {
        this.code = code ;
    }
    public String getCode() {
        return this.code;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public void setDiscountPercentage( BigDecimal discountPercentage ) {
        this.discountPercentage = discountPercentage ;
    }
    public BigDecimal getDiscountPercentage() {
        return this.discountPercentage;
    }

    public void setDiscountAmount( BigDecimal discountAmount ) {
        this.discountAmount = discountAmount ;
    }
    public BigDecimal getDiscountAmount() {
        return this.discountAmount;
    }

    public void setStartDate( LocalDate startDate ) {
        this.startDate = startDate ;
    }
    public LocalDate getStartDate() {
        return this.startDate;
    }

    public void setEndDate( LocalDate endDate ) {
        this.endDate = endDate ;
    }
    public LocalDate getEndDate() {
        return this.endDate;
    }

    public void setIsActive( boolean isActive ) {
        this.isActive = isActive ;
    }
    public boolean isIsActive() {
        return this.isActive;
    }

    public void setMaxUses( Integer maxUses ) {
        this.maxUses = maxUses ;
    }
    public Integer getMaxUses() {
        return this.maxUses;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Promotions[");
		sb.append("promotionId=").append(promotionId);
		sb.append(separator).append("code=").append(code);
		sb.append(separator).append("description=").append(description);
		sb.append(separator).append("discountPercentage=").append(discountPercentage);
		sb.append(separator).append("discountAmount=").append(discountAmount);
		sb.append(separator).append("startDate=").append(startDate);
		sb.append(separator).append("endDate=").append(endDate);
		sb.append(separator).append("isActive=").append(isActive);
		sb.append(separator).append("maxUses=").append(maxUses);
		sb.append("]");
		return sb.toString();
	}
}
