/*
 * Created on 2025-03-19 ( 17:24:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.time.LocalDateTime;
import javax.persistence.*;

/**
 * JPA entity class for "ReservedStock"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Reserved_Stock", schema="public", catalog="clothes_store_db" )
public class ReservedStock implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="Reservation_ID", nullable=false)
    private int        reservationId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Store_ID", nullable=false)
    private int        storeId ;

    @Column(name="Product_ID", nullable=false)
    private int        productId ;

    @Column(name="Quantity", nullable=false)
    private int        quantity ;

    @Column(name="Reserved_At", nullable=false)
    private LocalDateTime reservedAt ;

    @Column(name="Expires_At", nullable=false)
    private LocalDateTime expiresAt ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="Product_ID", referencedColumnName="Product_ID", insertable=false, updatable=false)
    private Product    product ; 

    @ManyToOne
    @JoinColumn(name="Store_ID", referencedColumnName="Store_ID", insertable=false, updatable=false)
    private Store      store ; 


    /**
     * Constructor
     */
    public ReservedStock() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setReservationId( int reservationId ) {
        this.reservationId = reservationId ;
    }
    public int getReservationId() {
        return this.reservationId;
    }

    public void setStoreId( int storeId ) {
        this.storeId = storeId ;
    }
    public int getStoreId() {
        return this.storeId;
    }

    public void setProductId( int productId ) {
        this.productId = productId ;
    }
    public int getProductId() {
        return this.productId;
    }

    public void setQuantity( int quantity ) {
        this.quantity = quantity ;
    }
    public int getQuantity() {
        return this.quantity;
    }

    public void setReservedAt( LocalDateTime reservedAt ) {
        this.reservedAt = reservedAt ;
    }
    public LocalDateTime getReservedAt() {
        return this.reservedAt;
    }

    public void setExpiresAt( LocalDateTime expiresAt ) {
        this.expiresAt = expiresAt ;
    }
    public LocalDateTime getExpiresAt() {
        return this.expiresAt;
    }

    //--- GETTERS FOR LINKS
    public Product getProduct() {
        return this.product;
    } 

    public Store getStore() {
        return this.store;
    } 

    //--- toString specific method
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("ReservedStock[");
		sb.append("reservationId=").append(reservationId);
		sb.append(separator).append("storeId=").append(storeId);
		sb.append(separator).append("productId=").append(productId);
		sb.append(separator).append("quantity=").append(quantity);
		sb.append(separator).append("reservedAt=").append(reservedAt);
		sb.append(separator).append("expiresAt=").append(expiresAt);
		sb.append("]");
		return sb.toString();
	}
}
