/*
 * Created on 2025-03-19 ( 17:24:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import javax.persistence.*;

/**
 * JPA entity class for "Return"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Return", schema="public", catalog="clothes_store_db" )
public class Return implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="Return_ID", nullable=false)
    private int        returnId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Order_ID", nullable=false)
    private int        orderId ;

    @Column(name="Product_ID", nullable=false)
    private int        productId ;

    @Column(name="Refunded_Amount", nullable=false)
    private BigDecimal refundedAmount ;

    @Column(name="Quantity_Returned", nullable=false)
    private int        quantityReturned ;

    @Column(name="Reason", nullable=false, length=255)
    private String     reason ;

    @Column(name="Return_Date", nullable=false)
    private LocalDate  returnDate ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="Order_ID", referencedColumnName="Order_ID", insertable=false, updatable=false)
    private CustomerOrder customerorder ; 

    @ManyToOne
    @JoinColumn(name="Product_ID", referencedColumnName="Product_ID", insertable=false, updatable=false)
    private Product    product ; 


    /**
     * Constructor
     */
    public Return() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setReturnId( int returnId ) {
        this.returnId = returnId ;
    }
    public int getReturnId() {
        return this.returnId;
    }

    public void setOrderId( int orderId ) {
        this.orderId = orderId ;
    }
    public int getOrderId() {
        return this.orderId;
    }

    public void setProductId( int productId ) {
        this.productId = productId ;
    }
    public int getProductId() {
        return this.productId;
    }

    public void setRefundedAmount( BigDecimal refundedAmount ) {
        this.refundedAmount = refundedAmount ;
    }
    public BigDecimal getRefundedAmount() {
        return this.refundedAmount;
    }

    public void setQuantityReturned( int quantityReturned ) {
        this.quantityReturned = quantityReturned ;
    }
    public int getQuantityReturned() {
        return this.quantityReturned;
    }

    public void setReason( String reason ) {
        this.reason = reason ;
    }
    public String getReason() {
        return this.reason;
    }

    public void setReturnDate( LocalDate returnDate ) {
        this.returnDate = returnDate ;
    }
    public LocalDate getReturnDate() {
        return this.returnDate;
    }

    //--- GETTERS FOR LINKS
    public CustomerOrder getCustomerorder() {
        return this.customerorder;
    } 

    public Product getProduct() {
        return this.product;
    } 

    //--- toString specific method
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Return[");
		sb.append("returnId=").append(returnId);
		sb.append(separator).append("orderId=").append(orderId);
		sb.append(separator).append("productId=").append(productId);
		sb.append(separator).append("refundedAmount=").append(refundedAmount);
		sb.append(separator).append("quantityReturned=").append(quantityReturned);
		sb.append(separator).append("reason=").append(reason);
		sb.append(separator).append("returnDate=").append(returnDate);
		sb.append("]");
		return sb.toString();
	}
}
