/*
 * Created on 2025-03-20 ( 10:03:16 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.util.Objects;  import java.time.LocalDateTime;
import javax.persistence.*;

/**
 * JPA entity class for "Reviews"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Reviews", schema="public", catalog="clothes_store_db" )
public class Reviews implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="Review_ID", nullable=false)
    private int        reviewId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Product_ID", nullable=false)
    private int        productId ;

    @Column(name="Customer_ID", nullable=false)
    private int        customerId ;

    @Column(name="Rating", nullable=false)
    private int        rating ;

    @Column(name="Comment", length=2147483647)
    private String     comment ;

    @Column(name="Review_Date", nullable=false)
    private LocalDateTime reviewDate ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="Customer_ID", referencedColumnName="Customer_ID", insertable=false, updatable=false)
    private Customer   customer ; 

    @ManyToOne
    @JoinColumn(name="Product_ID", referencedColumnName="Product_ID", insertable=false, updatable=false)
    private Product    product ; 


    /**
     * Constructor
     */
    public Reviews() {
        super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setReviewId( int reviewId ) {
        this.reviewId = reviewId ;
    }
    public int getReviewId() {
        return this.reviewId;
    }

    public void setProductId( int productId ) {
        this.productId = productId ;
    }
    public int getProductId() {
        return this.productId;
    }

    public void setCustomerId( int customerId ) {
        this.customerId = customerId ;
    }
    public int getCustomerId() {
        return this.customerId;
    }

    public void setRating( int rating ) {
        this.rating = rating ;
    }
    public int getRating() {
        return this.rating;
    }

    public void setComment( String comment ) {
        this.comment = comment ;
    }
    public String getComment() {
        return this.comment;
    }

    public void setReviewDate( LocalDateTime reviewDate ) {
        this.reviewDate = reviewDate ;
    }
    public LocalDateTime getReviewDate() {
        return this.reviewDate;
    }

    //--- GETTERS FOR LINKS
    public Customer getCustomer() {
        return this.customer;
    } 

    public Product getProduct() {
        return this.product;
    } 

    //--- toString specific method
    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Reviews[");
		sb.append("reviewId=").append(reviewId);
		sb.append(separator).append("productId=").append(productId);
		sb.append(separator).append("customerId=").append(customerId);
		sb.append(separator).append("rating=").append(rating);
		sb.append(separator).append("comment=").append(comment);
		sb.append(separator).append("reviewDate=").append(reviewDate);
		sb.append("]");
		return sb.toString();
	}

    //--- equals and hashCode methods
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Reviews that = (Reviews) o;
        return reviewId == that.reviewId#elseObjects.equals(reviewId, that.reviewId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(reviewId);
    }
}