/*
 * Created on 2025-03-19 ( 17:24:38 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.time.LocalDateTime;
import javax.persistence.*;

/**
 * JPA entity class for "Sessions"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Sessions", schema="public", catalog="clothes_store_db" )
public class Sessions implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="Session_ID", nullable=false, length=128)
    private String     sessionId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="User_ID", nullable=false)
    private int        userId ;

    @Column(name="Created_At", nullable=false)
    private LocalDateTime createdAt ;

    @Column(name="Expires_At", nullable=false)
    private LocalDateTime expiresAt ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="User_ID", referencedColumnName="User_ID", insertable=false, updatable=false)
    private Users      users ; 


    /**
     * Constructor
     */
    public Sessions() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setSessionId( String sessionId ) {
        this.sessionId = sessionId ;
    }
    public String getSessionId() {
        return this.sessionId;
    }

    public void setUserId( int userId ) {
        this.userId = userId ;
    }
    public int getUserId() {
        return this.userId;
    }

    public void setCreatedAt( LocalDateTime createdAt ) {
        this.createdAt = createdAt ;
    }
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setExpiresAt( LocalDateTime expiresAt ) {
        this.expiresAt = expiresAt ;
    }
    public LocalDateTime getExpiresAt() {
        return this.expiresAt;
    }

    //--- GETTERS FOR LINKS
    public Users getUsers() {
        return this.users;
    } 

    //--- toString specific method
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Sessions[");
		sb.append("sessionId=").append(sessionId);
		sb.append(separator).append("userId=").append(userId);
		sb.append(separator).append("createdAt=").append(createdAt);
		sb.append(separator).append("expiresAt=").append(expiresAt);
		sb.append("]");
		return sb.toString();
	}
}
