/*
 * Created on 2025-03-19 ( 17:24:38 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.time.LocalDateTime;
import javax.persistence.*;

/**
 * JPA entity class for "Shipping"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Shipping", schema="public", catalog="clothes_store_db" )
public class Shipping implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="Shipping_ID", nullable=false)
    private int        shippingId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Order_ID", nullable=false)
    private int        orderId ;

    @Column(name="Tracking_Number", length=50)
    private String     trackingNumber ;

    @Column(name="Shipping_Provider", length=50)
    private String     shippingProvider ;

    @Column(name="Shipped_Date")
    private LocalDateTime shippedDate ;

    @Column(name="Delivered_Date")
    private LocalDateTime deliveredDate ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="Order_ID", referencedColumnName="Order_ID", insertable=false, updatable=false)
    private CustomerOrder customerorder ; 


    /**
     * Constructor
     */
    public Shipping() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setShippingId( int shippingId ) {
        this.shippingId = shippingId ;
    }
    public int getShippingId() {
        return this.shippingId;
    }

    public void setOrderId( int orderId ) {
        this.orderId = orderId ;
    }
    public int getOrderId() {
        return this.orderId;
    }

    public void setTrackingNumber( String trackingNumber ) {
        this.trackingNumber = trackingNumber ;
    }
    public String getTrackingNumber() {
        return this.trackingNumber;
    }

    public void setShippingProvider( String shippingProvider ) {
        this.shippingProvider = shippingProvider ;
    }
    public String getShippingProvider() {
        return this.shippingProvider;
    }

    public void setShippedDate( LocalDateTime shippedDate ) {
        this.shippedDate = shippedDate ;
    }
    public LocalDateTime getShippedDate() {
        return this.shippedDate;
    }

    public void setDeliveredDate( LocalDateTime deliveredDate ) {
        this.deliveredDate = deliveredDate ;
    }
    public LocalDateTime getDeliveredDate() {
        return this.deliveredDate;
    }

    //--- GETTERS FOR LINKS
    public CustomerOrder getCustomerorder() {
        return this.customerorder;
    } 

    //--- toString specific method
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Shipping[");
		sb.append("shippingId=").append(shippingId);
		sb.append(separator).append("orderId=").append(orderId);
		sb.append(separator).append("trackingNumber=").append(trackingNumber);
		sb.append(separator).append("shippingProvider=").append(shippingProvider);
		sb.append(separator).append("shippedDate=").append(shippedDate);
		sb.append(separator).append("deliveredDate=").append(deliveredDate);
		sb.append("]");
		return sb.toString();
	}
}
