/*
 * Created on 2025-03-20 ( 10:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import java.io.Serializable;


/**
 * Composite primary key for entity "StoreInventory" ( stored in table "Store_Inventory" )
 *
 * @author Telosys
 *
 */
public class StoreInventoryId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private int        storeId ;
    
    private int        productId ;
    
    /**
     * Constructor
     */
    public StoreInventoryId() {
        super();
    }

    /**
     * Constructor with values
     * @param storeId 
     * @param productId 
     */
    public StoreInventoryId( Integer storeId, Integer productId ) {
        super();
        this.storeId = storeId ;
        this.productId = productId ;
    }
    
    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setStoreId( int value ) {
        this.storeId = value;
    }
    public int getStoreId() {
        return this.storeId;
    }

    public void setProductId( int value ) {
        this.productId = value;
    }
    public int getProductId() {
        return this.productId;
    }


    //--- equals METHOD
	@Override
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		StoreInventoryId other = (StoreInventoryId) obj; 
		//--- Attribute storeId
		if ( storeId != other.storeId ) return false ; 
		//--- Attribute productId
		if ( productId != other.productId ) return false ; 
		return true; 
	} 
    //--- hashCode METHOD
	@Override
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute storeId
		result = prime * result + storeId;
		//--- Attribute productId
		result = prime * result + productId;
		
		return result; 
	} 
    //--- toString METHOD
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("StoreInventory[");
		sb.append("storeId=").append(storeId);
		sb.append(separator).append("productId=").append(productId);
		sb.append("]");
		return sb.toString();
	}

}
