/*
 * Created on 2025-03-19 ( 17:24:38 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;


import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "StoreInventory"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Store_Inventory", schema="public", catalog="clothes_store_db" )
@IdClass(StoreInventoryId.class)
public class StoreInventory implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="Store_ID", nullable=false)
    private int        storeId ;

    @Id
    @Column(name="Product_ID", nullable=false)
    private int        productId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Quantity", nullable=false)
    private int        quantity ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="Product_ID", referencedColumnName="Product_ID", insertable=false, updatable=false)
    private Product    product ; 

    @ManyToOne
    @JoinColumn(name="Store_ID", referencedColumnName="Store_ID", insertable=false, updatable=false)
    private Store      store ; 


    /**
     * Constructor
     */
    public StoreInventory() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setStoreId( int storeId ) {
        this.storeId = storeId ;
    }
    public int getStoreId() {
        return this.storeId;
    }

    public void setProductId( int productId ) {
        this.productId = productId ;
    }
    public int getProductId() {
        return this.productId;
    }

    public void setQuantity( int quantity ) {
        this.quantity = quantity ;
    }
    public int getQuantity() {
        return this.quantity;
    }

    //--- GETTERS FOR LINKS
    public Product getProduct() {
        return this.product;
    } 

    public Store getStore() {
        return this.store;
    } 

    //--- toString specific method
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("StoreInventory[");
		sb.append("storeId=").append(storeId);
		sb.append(separator).append("productId=").append(productId);
		sb.append(separator).append("quantity=").append(quantity);
		sb.append("]");
		return sb.toString();
	}
}
