/*
 * Created on 2025-03-20 ( 10:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.util.Objects;  import javax.persistence.*;

/**
 * JPA entity class for "Storage"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Storage", schema="public", catalog="clothes_store_db" )
public class Storage implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="Storage_No", nullable=false)
    private int        storageNo ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Store_ID", nullable=false)
    private int        storeId ;

    @Column(name="Location", nullable=false, length=100)
    private String     location ;

    @Column(name="Reorder_Level", nullable=false)
    private int        reorderLevel ;

    @Column(name="Max_Stock", nullable=false)
    private int        maxStock ;

    @Column(name="Min_Stock", nullable=false)
    private int        minStock ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="Store_ID", referencedColumnName="Store_ID", insertable=false, updatable=false)
    private Store      store ; 


    /**
     * Constructor
     */
    public Storage() {
        super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setStorageNo( int storageNo ) {
        this.storageNo = storageNo ;
    }
    public int getStorageNo() {
        return this.storageNo;
    }

    public void setStoreId( int storeId ) {
        this.storeId = storeId ;
    }
    public int getStoreId() {
        return this.storeId;
    }

    public void setLocation( String location ) {
        this.location = location ;
    }
    public String getLocation() {
        return this.location;
    }

    public void setReorderLevel( int reorderLevel ) {
        this.reorderLevel = reorderLevel ;
    }
    public int getReorderLevel() {
        return this.reorderLevel;
    }

    public void setMaxStock( int maxStock ) {
        this.maxStock = maxStock ;
    }
    public int getMaxStock() {
        return this.maxStock;
    }

    public void setMinStock( int minStock ) {
        this.minStock = minStock ;
    }
    public int getMinStock() {
        return this.minStock;
    }

    //--- GETTERS FOR LINKS
    public Store getStore() {
        return this.store;
    } 

    //--- toString specific method
    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Storage[");
		sb.append("storageNo=").append(storageNo);
		sb.append(separator).append("storeId=").append(storeId);
		sb.append(separator).append("location=").append(location);
		sb.append(separator).append("reorderLevel=").append(reorderLevel);
		sb.append(separator).append("maxStock=").append(maxStock);
		sb.append(separator).append("minStock=").append(minStock);
		sb.append("]");
		return sb.toString();
	}

    //--- equals and hashCode methods
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Storage that = (Storage) o;
        return storageNo == that.storageNo#elseObjects.equals(storageNo, that.storageNo);
    }

    @Override
    public int hashCode() {
        return Objects.hash(storageNo);
    }
}