/*
 * Created on 2025-03-20 ( 10:03:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.util.Objects;  import javax.persistence.*;

/**
 * JPA entity class for "Supplier"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Supplier", schema="public", catalog="clothes_store_db" )
public class Supplier implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="Supplier_ID", nullable=false)
    private int        supplierId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Supplier_Name", nullable=false, length=100)
    private String     supplierName ;

    @Column(name="Email", nullable=false, length=255)
    private String     email ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Supplier() {
        super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setSupplierId( int supplierId ) {
        this.supplierId = supplierId ;
    }
    public int getSupplierId() {
        return this.supplierId;
    }

    public void setSupplierName( String supplierName ) {
        this.supplierName = supplierName ;
    }
    public String getSupplierName() {
        return this.supplierName;
    }

    public void setEmail( String email ) {
        this.email = email ;
    }
    public String getEmail() {
        return this.email;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Supplier[");
		sb.append("supplierId=").append(supplierId);
		sb.append(separator).append("supplierName=").append(supplierName);
		sb.append(separator).append("email=").append(email);
		sb.append("]");
		return sb.toString();
	}

    //--- equals and hashCode methods
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Supplier that = (Supplier) o;
        return supplierId == that.supplierId#elseObjects.equals(supplierId, that.supplierId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(supplierId);
    }
}