/*
 * Created on 2025-03-19 ( 17:24:39 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import javax.persistence.*;

/**
 * JPA entity class for "SupplyOrder"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Supply_Order", schema="public", catalog="clothes_store_db" )
public class SupplyOrder implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="Supply_Order_ID", nullable=false)
    private int        supplyOrderId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Supplier_ID", nullable=false)
    private int        supplierId ;

    @Column(name="Product_ID", nullable=false)
    private int        productId ;

    @Column(name="Employee_ID")
    private Integer    employeeId ;

    @Column(name="Quantity_Ordered", nullable=false)
    private int        quantityOrdered ;

    @Column(name="Price", nullable=false)
    private BigDecimal price ;

    @Column(name="Order_Date", nullable=false)
    private LocalDate  orderDate ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="Employee_ID", referencedColumnName="Employee_ID", insertable=false, updatable=false)
    private Employee   employee ; 

    @ManyToOne
    @JoinColumn(name="Product_ID", referencedColumnName="Product_ID", insertable=false, updatable=false)
    private Product    product ; 

    @ManyToOne
    @JoinColumn(name="Supplier_ID", referencedColumnName="Supplier_ID", insertable=false, updatable=false)
    private Supplier   supplier ; 


    /**
     * Constructor
     */
    public SupplyOrder() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setSupplyOrderId( int supplyOrderId ) {
        this.supplyOrderId = supplyOrderId ;
    }
    public int getSupplyOrderId() {
        return this.supplyOrderId;
    }

    public void setSupplierId( int supplierId ) {
        this.supplierId = supplierId ;
    }
    public int getSupplierId() {
        return this.supplierId;
    }

    public void setProductId( int productId ) {
        this.productId = productId ;
    }
    public int getProductId() {
        return this.productId;
    }

    public void setEmployeeId( Integer employeeId ) {
        this.employeeId = employeeId ;
    }
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    public void setQuantityOrdered( int quantityOrdered ) {
        this.quantityOrdered = quantityOrdered ;
    }
    public int getQuantityOrdered() {
        return this.quantityOrdered;
    }

    public void setPrice( BigDecimal price ) {
        this.price = price ;
    }
    public BigDecimal getPrice() {
        return this.price;
    }

    public void setOrderDate( LocalDate orderDate ) {
        this.orderDate = orderDate ;
    }
    public LocalDate getOrderDate() {
        return this.orderDate;
    }

    //--- GETTERS FOR LINKS
    public Employee getEmployee() {
        return this.employee;
    } 

    public Product getProduct() {
        return this.product;
    } 

    public Supplier getSupplier() {
        return this.supplier;
    } 

    //--- toString specific method
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("SupplyOrder[");
		sb.append("supplyOrderId=").append(supplyOrderId);
		sb.append(separator).append("supplierId=").append(supplierId);
		sb.append(separator).append("productId=").append(productId);
		sb.append(separator).append("employeeId=").append(employeeId);
		sb.append(separator).append("quantityOrdered=").append(quantityOrdered);
		sb.append(separator).append("price=").append(price);
		sb.append(separator).append("orderDate=").append(orderDate);
		sb.append("]");
		return sb.toString();
	}
}
