/*
 * Created on 2025-03-19 ( 17:24:39 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.time.LocalDateTime;
import javax.persistence.*;

/**
 * JPA entity class for "Users"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Users", schema="public", catalog="clothes_store_db" )
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="User_ID", nullable=false)
    private int        userId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Customer_ID", nullable=false)
    private int        customerId ;

    @Column(name="Email", nullable=false, length=255)
    private String     email ;

    @Column(name="Password_Hash", nullable=false, length=255)
    private String     passwordHash ;

    @Column(name="Role", nullable=false, length=20)
    private String     role ;

    @Column(name="Failed_Logins", nullable=false)
    private int        failedLogins ;

    @Column(name="Locked_Until")
    private LocalDateTime lockedUntil ;

    @Column(name="Created_At", nullable=false)
    private LocalDateTime createdAt ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="Customer_ID", referencedColumnName="Customer_ID", insertable=false, updatable=false)
    private Customer   customer ; 


    /**
     * Constructor
     */
    public Users() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setUserId( int userId ) {
        this.userId = userId ;
    }
    public int getUserId() {
        return this.userId;
    }

    public void setCustomerId( int customerId ) {
        this.customerId = customerId ;
    }
    public int getCustomerId() {
        return this.customerId;
    }

    public void setEmail( String email ) {
        this.email = email ;
    }
    public String getEmail() {
        return this.email;
    }

    public void setPasswordHash( String passwordHash ) {
        this.passwordHash = passwordHash ;
    }
    public String getPasswordHash() {
        return this.passwordHash;
    }

    public void setRole( String role ) {
        this.role = role ;
    }
    public String getRole() {
        return this.role;
    }

    public void setFailedLogins( int failedLogins ) {
        this.failedLogins = failedLogins ;
    }
    public int getFailedLogins() {
        return this.failedLogins;
    }

    public void setLockedUntil( LocalDateTime lockedUntil ) {
        this.lockedUntil = lockedUntil ;
    }
    public LocalDateTime getLockedUntil() {
        return this.lockedUntil;
    }

    public void setCreatedAt( LocalDateTime createdAt ) {
        this.createdAt = createdAt ;
    }
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    //--- GETTERS FOR LINKS
    public Customer getCustomer() {
        return this.customer;
    } 

    //--- toString specific method
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Users[");
		sb.append("userId=").append(userId);
		sb.append(separator).append("customerId=").append(customerId);
		sb.append(separator).append("email=").append(email);
		sb.append(separator).append("passwordHash=").append(passwordHash);
		sb.append(separator).append("role=").append(role);
		sb.append(separator).append("failedLogins=").append(failedLogins);
		sb.append(separator).append("lockedUntil=").append(lockedUntil);
		sb.append(separator).append("createdAt=").append(createdAt);
		sb.append("]");
		return sb.toString();
	}
}
