/*
 * Created on 2025-03-20 ( 10:03:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.util.Objects;  import java.time.LocalDate;
import javax.persistence.*;

/**
 * JPA entity class for "Wishlist"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Wishlist", schema="public", catalog="clothes_store_db" )
public class Wishlist implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="Wishlist_ID", nullable=false)
    private int        wishlistId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Customer_ID", nullable=false)
    private int        customerId ;

    @Column(name="Product_ID", nullable=false)
    private int        productId ;

    @Column(name="Added_Date", nullable=false)
    private LocalDate  addedDate ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="Customer_ID", referencedColumnName="Customer_ID", insertable=false, updatable=false)
    private Customer   customer ; 

    @ManyToOne
    @JoinColumn(name="Product_ID", referencedColumnName="Product_ID", insertable=false, updatable=false)
    private Product    product ; 


    /**
     * Constructor
     */
    public Wishlist() {
        super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setWishlistId( int wishlistId ) {
        this.wishlistId = wishlistId ;
    }
    public int getWishlistId() {
        return this.wishlistId;
    }

    public void setCustomerId( int customerId ) {
        this.customerId = customerId ;
    }
    public int getCustomerId() {
        return this.customerId;
    }

    public void setProductId( int productId ) {
        this.productId = productId ;
    }
    public int getProductId() {
        return this.productId;
    }

    public void setAddedDate( LocalDate addedDate ) {
        this.addedDate = addedDate ;
    }
    public LocalDate getAddedDate() {
        return this.addedDate;
    }

    //--- GETTERS FOR LINKS
    public Customer getCustomer() {
        return this.customer;
    } 

    public Product getProduct() {
        return this.product;
    } 

    //--- toString specific method
    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Wishlist[");
		sb.append("wishlistId=").append(wishlistId);
		sb.append(separator).append("customerId=").append(customerId);
		sb.append(separator).append("productId=").append(productId);
		sb.append(separator).append("addedDate=").append(addedDate);
		sb.append("]");
		return sb.toString();
	}

    //--- equals and hashCode methods
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Wishlist that = (Wishlist) o;
        return wishlistId == that.wishlistId#elseObjects.equals(wishlistId, that.wishlistId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(wishlistId);
    }
}